common:
  seed: 42

model:
  #model_path: models/vivit.h5
  num_classes: 11

train:
  epochs: 80
  batch_size: 32
  learning_rate: 1e-4
  weight_decay: 1e-5
  metrics_path: metrics/train.json
  #confusion_matrix_path: plots/test_conf_matrix.png

push_to_hub:
  feature_flag_push_to_hub: False
  repo_name: pablorodriper/video-vision_transformer